"""Symmetry groups: cyclic, dihedral, symmetric groups; Burnside lemma; orbit-stabilizer."""

from __future__ import annotations

import math
from typing import Sequence


class CyclicGroup:
    """The cyclic group C_n of order n (rotations of a regular n-gon).

    Elements are integers 0, 1, ..., n-1 representing rotations by 2πk/n.
    """

    def __init__(self, n: int):
        if n < 1:
            raise ValueError("n must be a positive integer")
        self.n = n

    @property
    def order(self) -> int:
        return self.n

    @property
    def elements(self) -> list[int]:
        return list(range(self.n))

    def compose(self, a: int, b: int) -> int:
        """Group operation: a ∘ b = (a + b) mod n."""
        return (a + b) % self.n

    def inverse(self, a: int) -> int:
        """Inverse element."""
        return (-a) % self.n

    def identity(self) -> int:
        return 0

    def generate(self, a: int) -> list[int]:
        """Subgroup generated by element a."""
        seen = set()
        current = self.identity()
        for _ in range(self.n):
            current = self.compose(current, a)
            if current in seen:
                break
            seen.add(current)
        return sorted(seen)

    def order_of(self, a: int) -> int:
        """Order of element a (smallest positive k with k*a ≡ 0 mod n)."""
        return self.n // math.gcd(a, self.n)


class DihedralGroup:
    """The dihedral group D_n of order 2n (symmetries of a regular n-gon).

    Elements are (r, s) where r ∈ {0,...,n-1} is rotation and s ∈ {0,1} is reflection.
    """

    def __init__(self, n: int):
        if n < 1:
            raise ValueError("n must be a positive integer")
        self.n = n

    @property
    def order(self) -> int:
        return 2 * self.n

    @property
    def elements(self) -> list[tuple[int, int]]:
        return [(r, s) for s in range(2) for r in range(self.n)]

    def compose(self, a: tuple[int, int], b: tuple[int, int]) -> tuple[int, int]:
        """Compose two symmetries: (r1,s1) ∘ (r2,s2)."""
        r1, s1 = a
        r2, s2 = b
        if s1 == 0:
            # Pure rotation then whatever b is
            return ((r1 + r2) % self.n, s2)
        else:
            # Reflection: (r1, 1) ∘ (r2, s2)
            if s2 == 0:
                return ((r1 - r2) % self.n, 1)
            else:
                return ((r1 - r2) % self.n, 0)

    def inverse(self, a: tuple[int, int]) -> tuple[int, int]:
        """Inverse of symmetry a."""
        r, s = a
        if s == 0:
            return ((-r) % self.n, 0)
        else:
            return (r, 1)  # Reflection is self-inverse in this encoding

    def identity(self) -> tuple[int, int]:
        return (0, 0)


class SymmetricGroup:
    """The symmetric group S_n of all permutations of {0, 1, ..., n-1}.

    Elements are tuples representing permutations (images of 0, 1, ..., n-1).
    """

    def __init__(self, n: int):
        if n < 1:
            raise ValueError("n must be a positive integer")
        self.n = n

    @property
    def order(self) -> int:
        return math.factorial(self.n)

    @property
    def elements(self) -> list[tuple[int, ...]]:
        return _all_permutations(self.n)

    def compose(self, a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
        """Compose permutations: (a ∘ b)(i) = a[b[i]]."""
        return tuple(a[b[i]] for i in range(self.n))

    def inverse(self, a: tuple[int, ...]) -> tuple[int, ...]:
        """Inverse permutation."""
        inv = [0] * self.n
        for i, v in enumerate(a):
            inv[v] = i
        return tuple(inv)

    def identity(self) -> tuple[int, ...]:
        return tuple(range(self.n))

    def sign(self, a: tuple[int, ...]) -> int:
        """Sign of permutation (+1 for even, -1 for odd)."""
        visited = [False] * self.n
        cycles = 0
        for i in range(self.n):
            if not visited[i]:
                cycles += 1
                j = i
                while not visited[j]:
                    visited[j] = True
                    j = a[j]
        # sign = (-1)^(n - cycles)
        return 1 if (self.n - cycles) % 2 == 0 else -1

    def cycle_type(self, a: tuple[int, ...]) -> tuple[int, ...]:
        """Return cycle type as sorted tuple of cycle lengths."""
        visited = [False] * self.n
        lengths = []
        for i in range(self.n):
            if not visited[i]:
                length = 0
                j = i
                while not visited[j]:
                    visited[j] = True
                    j = a[j]
                    length += 1
                lengths.append(length)
        return tuple(sorted(lengths, reverse=True))


def _all_permutations(n: int) -> list[tuple[int, ...]]:
    """Generate all permutations of {0, ..., n-1}."""
    if n == 0:
        return [()]
    if n == 1:
        return [(0,)]

    result = []

    def _permute(prefix: list[int], remaining: list[int]):
        if not remaining:
            result.append(tuple(prefix))
            return
        for i, val in enumerate(remaining):
            prefix.append(val)
            _permute(prefix, remaining[:i] + remaining[i + 1:])
            prefix.pop()

    _permute([], list(range(n)))
    return result


def burnside_lemma(group_elements: list, action, n_colors: int) -> int:
    """Count distinct colorings using Burnside's lemma.

    |X/G| = (1/|G|) Σ_{g∈G} |Fix(g)|

    Args:
        group_elements: List of group elements.
        action: Function (element, coloring) -> colored result.
            A coloring is a tuple of n_colors indices assigned to positions.
        n_colors: Number of available colors.

    Returns:
        Number of distinct colorings under the group action.
    """
    n = len(group_elements)
    if n == 0:
        return 0

    # For each group element, count fixed colorings
    # A coloring is fixed if action(g, coloring) == coloring
    # |Fix(g)| = n_colors^(# of cycles in the action of g)
    total_fixed = 0
    for g in group_elements:
        cycles = _count_cycles(group_elements, g, action)
        total_fixed += n_colors ** cycles

    return total_fixed // n


def _count_cycles(group_elements, g, action) -> int:
    """Count cycles of a group element's action."""
    # This is a simplified version — for permutation groups we count cycles directly
    if isinstance(g, tuple) and all(isinstance(x, int) for x in g):
        # It's a permutation — count its cycles
        n = len(g)
        visited = [False] * n
        cycles = 0
        for i in range(n):
            if not visited[i]:
                cycles += 1
                j = i
                while not visited[j]:
                    visited[j] = True
                    j = g[j]
        return cycles
    return 1  # Fallback


def orbit_stabilizer(group_elements: list, element, compose, action) -> dict:
    """Compute orbit and stabilizer using the orbit-stabilizer theorem.

    |G| = |Orb(x)| × |Stab(x)|

    Args:
        group_elements: List of all group elements.
        element: The object whose orbit/stabilizer we compute.
        compose: Group composition function (a, b) -> ab.
        action: Function (g, x) -> g·x.

    Returns:
        Dict with 'orbit', 'stabilizer', 'orbit_size', 'stabilizer_size', 'group_order'.
    """
    orbit = set()
    stabilizer = []

    for g in group_elements:
        acted = action(g, element)
        # Make hashable
        if isinstance(acted, list):
            acted = tuple(acted)
        orbit.add(acted)
        if acted == element or (isinstance(element, list) and acted == tuple(element)):
            stabilizer.append(g)

    return {
        "orbit": orbit,
        "stabilizer": stabilizer,
        "orbit_size": len(orbit),
        "stabilizer_size": len(stabilizer),
        "group_order": len(group_elements),
    }
